AllCops:
  Exclude:
    - "Gemfile"
    - "*.gemspec"
    - "spec/spec_helper.rb"
    - "config/**/*"
  UseCache: false
Style/Documentation:
  Exclude:
    - "lib/**/*"
Metrics/ModuleLength:
  Enabled: false
